name = "credence"
compatibility_date = "2026-08-17"
main = "_worker.js"

[assets]
directory = "."
binding = "ASSETS"

[env.production.vars]
PROD_BACKEND_URL = "https://credence-server-663899237633.us-central1.run.app"
DEV_BACKEND_URL = "https://credence-dev-663899237633.us-central1.run.app"

[env.dev.vars]
PROD_BACKEND_URL = "https://credence-server-663899237633.us-central1.run.app"
DEV_BACKEND_URL = "https://credence-dev-663899237633.us-central1.run.app"
